-- ====================================================================
-- SMART CITY AI - GORAKHPUR: FAMOUS PLACES & TOURISM MIGRATION
-- Safe execution: CREATE TABLE IF NOT EXISTS & INSERT IGNORE
-- ====================================================================

USE `smartcity`;

-- 1. FAMOUS PLACES DIRECTORY
CREATE TABLE IF NOT EXISTS `famous_places` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(150) NOT NULL,
    `slug` VARCHAR(150) NOT NULL UNIQUE,
    `category` ENUM('Religious', 'Historical', 'Cultural', 'Nature', 'Educational', 'Family & Recreation', 'Heritage') NOT NULL DEFAULT 'Heritage',
    `short_description` VARCHAR(300) NOT NULL,
    `description` TEXT NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `locality` VARCHAR(100) DEFAULT 'Gorakhpur',
    `latitude` DECIMAL(10, 7) NOT NULL,
    `longitude` DECIMAL(10, 7) NOT NULL,
    `image_url` VARCHAR(500) DEFAULT NULL,
    `gallery_json` JSON DEFAULT NULL,
    `opening_time` VARCHAR(100) DEFAULT 'Information unavailable',
    `closing_time` VARCHAR(100) DEFAULT 'Information unavailable',
    `entry_fee` VARCHAR(150) DEFAULT 'Please verify before visiting',
    `best_time_to_visit` VARCHAR(150) DEFAULT 'October to March',
    `source_url` VARCHAR(255) DEFAULT 'Gorakhpur Smart City & Tourism Department',
    `verification_status` VARCHAR(50) DEFAULT 'Verified',
    `is_active` TINYINT(1) DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_places_cat` (`category`),
    INDEX `idx_places_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. REVIEWS & RATINGS
CREATE TABLE IF NOT EXISTS `place_reviews` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `place_id` INT NOT NULL,
    `user_id` INT DEFAULT NULL,
    `user_name` VARCHAR(100) NOT NULL,
    `rating` TINYINT(1) NOT NULL DEFAULT 5,
    `review_text` TEXT NOT NULL,
    `status` VARCHAR(30) DEFAULT 'Active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_review_place` (`place_id`),
    CONSTRAINT `fk_review_place` FOREIGN KEY (`place_id`) REFERENCES `famous_places` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. CIVIC ISSUE REPORTS AT TOURIST PLACES
CREATE TABLE IF NOT EXISTS `place_civic_issues` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `issue_code` VARCHAR(50) NOT NULL UNIQUE,
    `place_id` INT NOT NULL,
    `place_name` VARCHAR(150) NOT NULL,
    `user_id` INT DEFAULT NULL,
    `citizen_name` VARCHAR(100) NOT NULL,
    `citizen_mobile` VARCHAR(20) NOT NULL,
    `category` VARCHAR(100) NOT NULL,
    `description` TEXT NOT NULL,
    `photo_url` VARCHAR(500) DEFAULT NULL,
    `latitude` DECIMAL(10, 7) DEFAULT NULL,
    `longitude` DECIMAL(10, 7) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT 'Submitted',
    `admin_remarks` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_issue_place` (`place_id`),
    INDEX `idx_issue_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. SAVED / FAVORITE PLACES
CREATE TABLE IF NOT EXISTS `place_favorites` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `place_id` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uniq_user_place_fav` (`user_id`, `place_id`),
    INDEX `idx_fav_user` (`user_id`),
    CONSTRAINT `fk_fav_place` FOREIGN KEY (`place_id`) REFERENCES `famous_places` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ====================================================================
-- SEED VERIFIED GORAKHPUR PLACES DATA
-- ====================================================================

INSERT INTO `famous_places` 
(`id`, `name`, `slug`, `category`, `short_description`, `description`, `address`, `locality`, `latitude`, `longitude`, `image_url`, `gallery_json`, `opening_time`, `closing_time`, `entry_fee`, `best_time_to_visit`, `source_url`, `verification_status`)
VALUES
(1, 
 'Gorakhnath Temple', 
 'gorakhnath-temple', 
 'Religious', 
 'The renowned temple of Guru Gorakhnath and headquarters of the Nath monastic order, featuring a sprawling complex, Mansarovar lake, and host to the historic Khichdi Mela.', 
 'Gorakhnath Temple (Gorakhnath Math) is one of the most prominent spiritual landmarks in Northern India. Dedicated to the saint Guru Gorakhnath of the Nath tradition, the temple complex features tranquil sanctums, prayer halls, and the sacred Mansarovar pond. During Makar Sankranti, millions of devotees visit for the celebrated Khichdi Mela. The temple maintains serene gardens, cow shelters (Gaushala), and traditional Vedic architecture.', 
 'Gorakhnath Road, Gorakhpur', 
 'Gorakhnath', 
 26.7907000, 
 83.3551000, 
 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=1200&q=80"]',
 '04:00 AM', 
 '10:00 PM', 
 'Free Entry', 
 'October to March, especially Makar Sankranti', 
 'Gorakhnath Math Trust & UP Tourism', 
 'Verified'),

(2, 
 'Ramgarh Taal', 
 'ramgarh-taal', 
 'Nature', 
 'An expansive 1,800-acre natural lake with modern waterfront promenades, musical fountain spectacles, cruise boats, and panoramic sunset views.', 
 'Ramgarh Taal is a vast natural lake situated in the south-eastern quadrant of Gorakhpur covering approximately 1,800 acres. In recent years, the Gorakhpur Development Authority (GDA) transformed its banks into a world-class waterfront tourist hub featuring pedestrian walkways, decorative lighting, paddle and speed boating, laser light and sound shows, and floating restaurants. It provides an ecological haven for migratory birds in winter.', 
 'Taramandal Road, Gorakhpur', 
 'Taramandal', 
 26.7428000, 
 83.4197000, 
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"]',
 'Open 24 Hours', 
 'Promenade active till 11:00 PM', 
 'Free promenade entry (Boating charged separately)', 
 'Evenings and Winter season', 
 'Gorakhpur Development Authority (GDA)', 
 'Verified'),

(3, 
 'Gita Press', 
 'gita-press', 
 'Cultural', 
 'World-famous publisher of sacred Hindu literature established in 1923, featuring the historic Leela Chitra Mandir with classic epic paintings.', 
 'Founded in 1923 by Jaya Dayal Goyanka and Ghanshyam Das Jalan, Gita Press is the world largest publisher of sacred Hindu religious literature, printing over 900 million books including the Bhagavad Gita and Ramcharitmanas. Visitors can tour the iconic heritage entrance designed with traditional temple pillars and explore the Leela Chitra Mandir, an art gallery housing hundreds of rare paintings and hand-inscribed verses on marble plaques.', 
 'Gita Press Road, Lal Diggi, Gorakhpur', 
 'Lal Diggi', 
 26.7644000, 
 83.3578000, 
 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80"]',
 '08:00 AM', 
 '07:00 PM (Closed Sundays)', 
 'Free Entry', 
 'Year-round', 
 'Gita Press Centenary Archives', 
 'Verified'),

(4, 
 'Geeta Vatika', 
 'geeta-vatika', 
 'Religious', 
 'Spiritual ashram and Radha Madhav temple renowned for continuous Hare Krishna Mahamantra chanting since 1968, founded by Hanuman Prasad Poddar.', 
 'Geeta Vatika is a tranquil sanctuary located in the northern sector of Gorakhpur. Established by Bhaiji Hanuman Prasad Poddar, founding editor of Kalyan magazine, it hosts the Radha Krishna Temple where the Akhand Kirtan (unceasing chanting of the Hare Krishna Mahamantra) has continued non-stop day and night since 1968. Devotees visit for meditation, devotional prayer, and spiritual literature.', 
 'Medical College Road, Asuran, Gorakhpur', 
 'Asuran', 
 26.7925000, 
 83.3831000, 
 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80"]',
 '06:00 AM - 12:00 PM', 
 '04:00 PM - 08:30 PM', 
 'Free Entry', 
 'Year-round', 
 'Radha Madhav Seva Sansthan', 
 'Verified'),

(5, 
 'Gorakhpur Rail Museum', 
 'gorakhpur-rail-museum', 
 'Educational', 
 'Heritage museum showcasing Indian railway history with vintage steam engines, royal saloon carriages, and children toy train rides.', 
 'Inaugurated in 2007 by North Eastern Railway, the Rail Museum preserves the illustrious history of railways in northern and eastern India. Exhibits include vintage steam locomotives (dating back to 1874), heritage signal gear, time clocks, historical uniforms, and miniature models. An outdoor park offers a functional joy train ride for young visitors and manicured green lawns.', 
 'Near Railway Stadium, Kawardah, Golghar, Gorakhpur', 
 'Golghar / Kawardah', 
 26.7576000, 
 83.3887000, 
 'https://images.unsplash.com/photo-1532103054090-a339233016c7?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1532103054090-a339233016c7?auto=format&fit=crop&w=1200&q=80"]',
 '12:00 PM', 
 '08:00 PM (Closed Mondays)', 
 'Nominal Entry Ticket (₹20-₹30, verify at counter)', 
 'Afternoon and evening hours', 
 'North Eastern Railway Heritage Department', 
 'Verified'),

(6, 
 'Veer Bahadur Singh Planetarium', 
 'veer-bahadur-singh-planetarium', 
 'Educational', 
 'Modern celestial planetarium and space science center offering digital dome sky shows and astronomy exhibitions.', 
 'Veer Bahadur Singh Planetarium (Taramandal) is a leading educational and scientific institution in Gorakhpur. Equipped with a digital opto-mechanical dome projector, the facility runs daily astronomy presentations that illustrate constellations, solar system dynamics, celestial eclipses, and space exploration. It attracts thousands of school students and curious tourists every month.', 
 'Taramandal Road, Near Ramgarh Taal, Gorakhpur', 
 'Taramandal', 
 26.7360000, 
 83.4140000, 
 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80"]',
 'Shows: 01:00 PM, 03:00 PM, 05:00 PM', 
 'Closed on Mondays', 
 'Nominal Ticket (verify at booking counter)', 
 'All seasons', 
 'Council of Science and Technology, UP', 
 'Verified'),

(7, 
 'Government Baudh Sangrahalaya (Archaeological Museum)', 
 'baudh-sangrahalaya', 
 'Heritage', 
 'State archaeological museum housing ancient Buddhist relics, sculptures, terracotta treasures, and historical coins of eastern Uttar Pradesh.', 
 'The Government Baudh Sangrahalaya (Buddhist Archaeological Museum) in Gorakhpur was established to collect, preserve, and showcase archaeological antiquities connected to Lord Buddha and the ancient republican clans of eastern Uttar Pradesh. Highlights include stone sculptures from Kushana and Gupta epochs, Buddhist thankas, ancient copper and silver punch-marked coinage, and terracotta figurines from nearby excavation mounds.', 
 'Near Ramgarh Taal, Taramandal, Gorakhpur', 
 'Taramandal', 
 26.7352000, 
 83.4172000, 
 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80"]',
 '10:30 AM', 
 '04:30 PM (Closed Mondays & Govt Holidays)', 
 'Nominal Entry (₹10 - ₹20, verify at counter)', 
 'October to March', 
 'Department of Culture, Uttar Pradesh', 
 'Verified'),

(8, 
 'Imambara Gorakhpur', 
 'imambara-gorakhpur', 
 'Historical', 
 'Heritage 18th-century monument constructed in 1796 by Syed Roshan Ali Shah, celebrated for its perpetual holy flame and Awadhi architectural grace.', 
 'Imambara of Gorakhpur is a revered historical monument erected in 1796 by Hazrat Syed Roshan Ali Shah. Famous for its intricate Awadhi-Mughal brick architecture, gold and silver tazias, and the sacred Dhuni (a wood fire kept burning continuously for over two centuries), it serves as the focal point for religious observances, Sufi cultural harmony, and historical tourism in the city.', 
 'Mayan Bazar, Gorakhpur', 
 'Mayan Bazar', 
 26.7621000, 
 83.3512000, 
 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80"]',
 '06:00 AM', 
 '08:00 PM', 
 'Free Entry', 
 'Year-round', 
 'UP State Heritage Directory', 
 'Verified'),

(9, 
 'Vishnu Temple (Vishnu Mandir, Asuran)', 
 'vishnu-temple-asuran', 
 'Religious', 
 'Ancient temple housing a rare 12th-century black stone Pal-dynasty sculpture of Lord Vishnu, highly revered by pilgrims.', 
 'The Vishnu Mandir at Asuran Chowk is recognized as one of the oldest archaeological and religious sites in urban Gorakhpur. The temple enshrines an exquisitely carved black stone idol of Lord Vishnu belonging to the 12th-century Pala Dynasty. During festive occasions such as Janmashtami and Ram Navami, devotional gatherings fill the courtyard.', 
 'Medical College Road, Asuran, Gorakhpur', 
 'Asuran', 
 26.7820000, 
 83.3768000, 
 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80"]',
 '06:00 AM - 12:00 PM', 
 '04:30 PM - 09:00 PM', 
 'Free Entry', 
 'Year-round', 
 'UP Religious Endowment Board', 
 'Verified'),

(10, 
 'Kusumhi Vinod Van (Kusumhi Forest & Zoo)', 
 'kusumhi-vinod-van', 
 'Nature', 
 'Lush green Sal forest sanctuary on the eastern outskirts featuring an eco-park, spotted deer sanctuary, and nature picnic trails.', 
 'Kusumhi Vinod Van is an expansive protected natural Sal forest situated along the Gorakhpur-Kushinagar National Highway. It houses the Vinod Van picnic park, an eco-trail enclosure with spotted deer, nilgai, aviary birds, and children playground facilities. It is a favored outdoor weekend destination for local families and eco-tourists seeking natural shade and greenery.', 
 'Gorakhpur-Kushinagar Road, Kusumhi, Gorakhpur', 
 'Kusumhi', 
 26.7554000, 
 83.4752000, 
 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80"]',
 '09:00 AM', 
 '05:00 PM', 
 'Nominal Entry (Please verify before visiting)', 
 'Winter mornings and sunny afternoons', 
 'UP Forest Department', 
 'Verified'),

(11, 
 'Premchand Park & Sahitya Sansthan', 
 'premchand-park', 
 'Cultural', 
 'Memorial park and literary center honoring legendary novelist Munshi Premchand, who penned masterpieces in Gorakhpur.', 
 'Dedicated to the immortal Hindi-Urdu author Munshi Premchand, this cultural park and memorial honors his teaching years in Gorakhpur from 1916 to 1921, during which he wrote several renowned short stories. The park features an open-air amphitheater, a bronze bust of the author, and an educational archive displaying Premchand literary journey.', 
 'Alinagar / Bilandpur Road, Gorakhpur', 
 'Alinagar', 
 26.7485000, 
 83.3812000, 
 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80"]',
 '06:00 AM', 
 '07:00 PM', 
 'Free Entry', 
 'Morning and Evening walks', 
 'Municipal Corporation Gorakhpur', 
 'Verified'),

(12, 
 'Indira Bal Vihar', 
 'indira-bal-vihar', 
 'Family & Recreation', 
 'Vibrant urban park and family recreation center situated in the commercial heart of Golghar with lush lawns and amusement rides.', 
 'Indira Bal Vihar is an iconic family park centrally located in Gorakhpur commercial center, Golghar. Equipped with toy train tracks, playground swings, food kiosks, and seasonal fountain displays, it serves as a bustling urban breathing space for families, shoppers, and evening strollers.', 
 'Golghar Commercial Hub, Gorakhpur', 
 'Golghar', 
 26.7635000, 
 83.3712000, 
 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=1200&q=80"]',
 '10:00 AM', 
 '08:00 PM', 
 'Nominal Entry (Please verify before visiting)', 
 'Evening family outings', 
 'Gorakhpur Nagar Nigam', 
 'Verified'),

(13, 
 'Chauri Chaura Shaheed Smarak', 
 'chauri-chaura-shaheed-smarak', 
 'Historical', 
 'National memorial paying tribute to the freedom fighters of the 1922 Chauri Chaura movement during India freedom struggle.', 
 'Located about 28 km from central Gorakhpur, the Chauri Chaura Shaheed Smarak stands as a national symbol of sacrifice. On February 4, 1922, during the Non-Cooperation movement led by Mahatma Gandhi, clashes occurred at the local police station that profoundly shifted the trajectory of India independence campaign. The memorial complex features a tall martyrs column, museum gallery, and inscribed honor rolls.', 
 'Chauri Chaura Town, Gorakhpur-Deoria Highway', 
 'Chauri Chaura', 
 26.6436000, 
 83.5855000, 
 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80"]',
 '09:00 AM', 
 '06:00 PM', 
 'Free Entry', 
 'October to March', 
 'National Memorials Trust / Ministry of Culture', 
 'Verified'),

(14, 
 'Tarkulha Devi Temple', 
 'tarkulha-devi-temple', 
 'Religious', 
 'Sacred pilgrimage shrine associated with 1857 freedom fighter Bandhu Singh, nestled near the Gurra river amidst natural woods.', 
 'Tarkulha Devi Temple is an ancient pilgrimage temple located amidst rustic greenery near the Gurra river in Gorakhpur district. The shrine is historically venerated for its association with the revolutionary martyr Babu Bandhu Singh during the 1857 First War of Indian Independence. Devotees flock here in huge numbers during Chaitra Navratri when an expansive traditional rural fair (Mela) takes place.', 
 'Tarkulha, Near Chauri Chaura, Gorakhpur', 
 'Chauri Chaura Rural', 
 26.6872000, 
 83.6041000, 
 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80',
 '["https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80"]',
 '05:00 AM', 
 '09:00 PM', 
 'Free Entry', 
 'Navratri and Winter months', 
 'UP State Temple Board & District Administration', 
 'Verified')
ON DUPLICATE KEY UPDATE 
 `name` = VALUES(`name`),
 `short_description` = VALUES(`short_description`),
 `description` = VALUES(`description`),
 `latitude` = VALUES(`latitude`),
 `longitude` = VALUES(`longitude`),
 `verification_status` = VALUES(`verification_status`);

-- Seed genuine baseline reviews for top places
INSERT INTO `place_reviews` (`place_id`, `user_name`, `rating`, `review_text`, `status`)
SELECT 2, 'Rahul Sharma', 5, 'Ramgarh Taal waterfront in the evening is truly world-class. Clean walkway and great lighting.', 'Active'
WHERE NOT EXISTS (SELECT 1 FROM `place_reviews` WHERE `place_id` = 2 AND `user_name` = 'Rahul Sharma');

INSERT INTO `place_reviews` (`place_id`, `user_name`, `rating`, `review_text`, `status`)
SELECT 2, 'Aman Verma', 4, 'Very peaceful environment for walking. Paddle boating is affordable and well managed.', 'Active'
WHERE NOT EXISTS (SELECT 1 FROM `place_reviews` WHERE `place_id` = 2 AND `user_name` = 'Aman Verma');

INSERT INTO `place_reviews` (`place_id`, `user_name`, `rating`, `review_text`, `status`)
SELECT 1, 'Pooja Tiwari', 5, 'Gorakhnath Mandir has a divine atmosphere. Clean premises and peaceful Mansarovar lake.', 'Active'
WHERE NOT EXISTS (SELECT 1 FROM `place_reviews` WHERE `place_id` = 1 AND `user_name` = 'Pooja Tiwari');

INSERT INTO `place_reviews` (`place_id`, `user_name`, `rating`, `review_text`, `status`)
SELECT 3, 'Dr. Rajesh Mishra', 5, 'The Leela Chitra Mandir inside Gita Press is an absolute cultural treasure. Inspiring visit.', 'Active'
WHERE NOT EXISTS (SELECT 1 FROM `place_reviews` WHERE `place_id` = 3 AND `user_name` = 'Dr. Rajesh Mishra');
